package:
  name: 'nionswift-usim'
  version: '5.4.2'

source:
  git_rev: 5.4.2
  git_url: https://github.com/nion-software/nionswift-usim.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.11
    - nionswift-instrumentation >=23.3,<24.0

test:
  imports:
    - nion.usim_device
    - nionswift_plugin.usim
    - nionswift_plugin.usim.test

about:
  home: https://github.com/nion-software/nionswift-usim
  license: GPL-3.0
  summary: "A Nion Swift package to simulate a STEM microscope, scanner, and cameras"
  description: "A Nion Swift package to simulate a STEM microscope, scanner, and cameras"

extra:
  recipe-maintainers:
    cmeyer
