package:
  name: 'nionswift-usim'
  version: '0.4.1'

source:
  git_rev: 0.4.1
  git_url: https://github.com/nion-software/nionswift-usim.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  include_recipe: False

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python >=3.8
    - nionswift >=0.16.0,<0.17.0
    - nionswift-instrumentation >=0.20.1,<0.21.0

test:
  imports:
    - nionswift_plugin.usim
    - nionswift_plugin.usim.test

about:
  home: https://github.com/nion-software/nionswift-usim
  license: GPL-3.0
  summary: "A Nion Swift package to simulate a STEM microscope, scanner, and cameras"
  description: "A Nion Swift package to simulate a STEM microscope, scanner, and cameras"

extra:
  recipe-maintainers:
    cmeyer
